version: "3.8"

services:
  web:
    build:
      context: .
    container_name: web
    image: bathroom-log
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./logs:/logs
      - ./views:/views
      - ./public:/public
    networks:
      - app-network
    ports:
      - "3000:3000"
    expose:
      - 3000

networks:
  app-network:
    driver: bridge